# Generated by Django 3.0.7 on 2020-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='total_employees',
            field=models.IntegerField(null=True),
        ),
    ]
