# Generated by Django 3.0.7 on 2020-06-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200607_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='locality',
            new_name='address',
        ),
    ]
