# Generated by Django 3.0.7 on 2020-06-18 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0003_auto_20200608_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='password',
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
