# Generated by Django 3.0.7 on 2020-07-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20200618_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='total_employees',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
