# Generated by Django 3.0.7 on 2020-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20200728_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='total_employees',
        ),
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='processing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
