# Generated by Django 3.0.7 on 2020-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='individual',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
