# Generated by Django 3.0.7 on 2020-11-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_auto_20201129_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='address_2',
        ),
    ]
