# Generated by Django 3.0.7 on 2021-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_auto_20201129_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=9, null=True),
        ),
    ]
