# Generated by Django 3.0.7 on 2021-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_auto_20210107_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
