# Generated by Django 3.0.7 on 2021-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_auto_20210107_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='address',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='employer',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='pcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='pcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
