# Generated by Django 3.0.7 on 2021-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0014_auto_20210107_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
