# Generated by Django 3.0.7 on 2021-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_auto_20210107_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='pcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='pcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
