# Generated by Django 3.1.3 on 2021-01-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_auto_20210110_2257'),
        ('employers', '0016_auto_20210110_0848'),
    ]

    operations = [
    ]
