# Generated by Django 3.1.3 on 2021-01-22 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(default='', max_length=100)),
                ('registered_business_name', models.CharField(default='', max_length=100)),
                ('registration_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_Number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('category', models.CharField(blank='True', choices=[('Home', 'Home'), ('Office', 'Office'), ('Health & Fitness', 'Health & Fitness'), ('Event', 'Event'), ('Lesson', 'Lesson')], default='', max_length=100)),
                ('service_type', models.CharField(blank='True', choices=[('Home', (('catering', 'Catering'), ('cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Pet grooming', 'Pet grooming'), ('Lighting & Wiring', 'Lighting & Wiring'), ('Renovation & Improvement', 'Renovation& Improvement'))), ('Office', (('Pest Control', 'Pest Control'), ('Office Maintenance', 'Office Maintenance'), ('Office Space Rental', 'Office Space Rental'), ('Hardware/Software Support', 'Hardware/Software Support'))), ('Event', (('Catering', 'Catering'), ('Wedding', 'Wedding'), ('Entertainment', 'Entertainment'), ('Beauty & Salon', 'Beauty & Salon'), ('Photographers & Videographers', 'Photographer & Videographers'))), ('Lessons', (('Academic', 'Academic'), ('Language', 'Language'), ('Lifestyle & Hobby', 'Lifestyle & Hobby'))), ('Health & Fitness', (('Personal Training', 'Personal Training'), ('Rehabilitation & Wellness', 'Rehabilitation & Wellness')))], default='', max_length=100)),
                ('services_offer', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank='True', default='', max_length=100)),
                ('company_name', models.CharField(blank='True', default='', max_length=100)),
                ('country', models.CharField(blank='True', default='', max_length=100)),
                ('state', models.CharField(blank='True', default='', max_length=100)),
                ('duration', models.CharField(blank='True', default='', max_length=100)),
                ('specialization', models.CharField(blank='True', choices=[('Accounting/Finance', 'Accounting/Finance'), ('Admin/Human Resources', 'Admin/Human Resources'), ('Sales/Marketing', 'Sales/Marketing'), ('Arts/Media/Communications', 'Arts/Media/Communications'), ('Services', 'Services'), ('Hotel/Restaurant', 'Hotel/Restaurant'), ('Education/Training', 'Education/Training'), ('Computer/Information Technology', 'Computer/Information Technology'), ('Engineering', 'Engineering'), ('Manufacturing', 'Manufacturing'), ('Building/Construction', 'Building/Construction'), ('Sciences', 'Sciences'), ('Healthcare', 'Healthcare'), ('Others', 'Others')], default='', max_length=100)),
                ('industry', models.CharField(blank='True', default='', max_length=100)),
                ('position_level', models.CharField(blank='True', choices=[('Senior Manager', 'Senior Manager'), ('Manager', 'Manager'), ('Senior Executive', 'Senior Executive'), ('Junior Executive', 'Junior Executive'), ('Fresh / Entry Level', 'Fresh / Entry Level'), ('Non-Executive', 'Non-Executive')], default='', max_length=100)),
                ('description', models.CharField(blank='True', default='', max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank='True', default='', max_length=100)),
                ('university_location', models.CharField(blank='True', default='', max_length=100)),
                ('graduation_date', models.CharField(blank='True', max_length=20)),
                ('qualification', models.CharField(blank='True', choices=[('Primary/Secondary School/SPM/O Level', 'Primary/Secondary School/SPM/O Level'), ('Higher Secondary/STPM/A Level/Pre-U', 'Higher Secondary/STPM/A Level/Pre-U'), ('Professional Certificate', 'Professional Certificate'), ('Diploma', 'Diploma'), ('Advanced/Higher/Graduate Diploma', 'Advanced/Higher/Graduate Diploma'), ('Bachelor Degree', 'Bachelor Degree'), ('Post Graduate Degree', 'Post Graduate Degree'), ('Professional Degree', 'Professional Degree'), ('Master Degree', 'Master Degree'), ('Doctorate (PHD)', 'Doctorate (PHD)')], default='', max_length=100)),
                ('field_of_study', models.CharField(blank='True', choices=[('Accounting/Finance', 'Accounting/Finance'), ('Admin/Human Resources', 'Admin/Human Resources'), ('Sales/Marketing', 'Sales/Marketing'), ('Arts/Media/Communications', 'Arts/Media/Communications'), ('Services', 'Services'), ('Hotel/Restaurant', 'Hotel/Restaurant'), ('Education/Training', 'Education/Training'), ('Computer/Information Technology', 'Computer/Information Technology'), ('Engineering', 'Engineering'), ('Manufacturing', 'Manufacturing'), ('Building/Construction', 'Building/Construction'), ('Sciences', 'Sciences'), ('Healthcare', 'Healthcare'), ('Others', 'Others')], default='', max_length=100)),
                ('title', models.CharField(blank='True', default='', max_length=100)),
                ('grade', models.CharField(blank='True', choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C'), ('Grade D', 'Grade D'), ('1st Class', '1st Class'), ('2nd Class Upper', '2nd Class Upper'), ('2nd Class Lower', '2nd Class Lower'), ('3rd Class', '3rd Class'), ('Pass/Non-gradable', 'Pass/Non-gradable'), ('Fail', 'Fail'), ('Incomplete', 'Incomplete'), ('On-going', 'On-going')], default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('phone_Number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('skills', models.CharField(blank='True', default='', max_length=100)),
                ('languages', models.CharField(blank='True', default='', max_length=100)),
                ('prefered_work_location', models.CharField(blank='True', choices=[('Penang', 'Penang'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Selangor', 'Selangor'), ('Kedah', 'Kedah'), ('Perlis', 'Perlis'), ('Perak', 'Perak'), ('Kelantan', 'Kelantan'), ('Terengganu', 'Terengganu'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Melaka', 'Melaka'), ('Pahang', 'Pahang'), ('Sarawak', 'Sarawak'), ('Sabah', 'Sabah'), ('Johor', 'Johor'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya')], default='', max_length=100)),
                ('expected_salary', models.IntegerField(blank='True', default=0)),
                ('resume', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('full_time', models.BooleanField(default=True)),
                ('part_time', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
