# Generated by Django 3.1.3 on 2021-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='languages',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prefered_work_location',
            field=models.CharField(blank='True', choices=[('Penang', 'Penang'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Selangor', 'Selangor'), ('Kedah', 'Kedah'), ('Perlis', 'Perlis'), ('Perak', 'Perak'), ('Kelantan', 'Kelantan'), ('Terengganu', 'Terengganu'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Melaka', 'Melaka'), ('Pahang', 'Pahang'), ('Sarawak', 'Sarawak'), ('Sabah', 'Sabah'), ('Johor', 'Johor'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
    ]
