# Generated by Django 3.1.3 on 2021-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210123_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_exp',
            name='company_name',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_exp',
            name='country',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_exp',
            name='description',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_exp',
            name='industry',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_exp',
            name='position_title',
            field=models.CharField(blank='True', default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_exp',
            name='specialization',
            field=models.CharField(blank='True', choices=[('Accounting/Finance', 'Accounting/Finance'), ('Admin/Human Resources', 'Admin/Human Resources'), ('Sales/Marketing', 'Sales/Marketing'), ('Arts/Media/Communications', 'Arts/Media/Communications'), ('Services', 'Services'), ('Hotel/Restaurant', 'Hotel/Restaurant'), ('Education/Training', 'Education/Training'), ('Computer/Information Technology', 'Computer/Information Technology'), ('Engineering', 'Engineering'), ('Manufacturing', 'Manufacturing'), ('Building/Construction', 'Building/Construction'), ('Sciences', 'Sciences'), ('Healthcare', 'Healthcare'), ('Others', 'Others')], default='', max_length=1000),
        ),
    ]
