# Generated by Django 3.1.5 on 2021-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDesc',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('jobdesc', models.FileField(upload_to='jobdesc/', verbose_name='Upload Job Description')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumeid', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, unique=True, upload_to='resumes/', verbose_name='Upload Resumes')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education')),
                ('skills', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Skills')),
                ('company_name', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Company Name')),
                ('designation', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Designation')),
                ('experience', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Experience')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Shortlisted', 'Shortlisted')], default='Available', max_length=20)),
            ],
        ),
    ]
