# Generated by Django 3.1.5 on 2021-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdesc',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='jobdesc',
            name='jobdesc',
            field=models.FileField(null=True, unique=True, upload_to='jobdesc/', verbose_name='Upload Job Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, unique=True, upload_to='resumes/', verbose_name='Upload Resumes'),
        ),
    ]
