# Generated by Django 3.1.3 on 2021-01-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0002_auto_20210107_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdesc',
            name='jobdesc',
            field=models.FileField(unique=True, upload_to='jobdesc/', verbose_name='Upload Job Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(unique=True, upload_to='resumes/', verbose_name='Upload Resumes'),
        ),
    ]
