# Generated by Django 3.1.3 on 2021-01-12 15:55

from django.db import migrations, models
import resumeanalyzer.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0003_auto_20210108_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdesc',
            name='jobdesc',
            field=models.FileField(storage=resumeanalyzer.models.FailOnDuplicateFileSystemStorage(), unique=True, upload_to='jobdesc/', verbose_name='Upload Job Description'),
        ),
        migrations.AlterField(
            model_name='jobdesc',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(storage=resumeanalyzer.models.FailOnDuplicateFileSystemStorage(), unique=True, upload_to='resumes/', verbose_name='Upload Resumes'),
        ),
    ]
