# Generated by Django 3.1.3 on 2021-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0004_auto_20210112_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdesc',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Title'),
        ),
    ]
