# Generated by Django 3.1.3 on 2021-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0005_auto_20210113_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdesc',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
