# Generated by Django 3.1.3 on 2021-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0007_auto_20210113_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='note',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Note'),
        ),
    ]
