# Generated by Django 3.1.3 on 2021-01-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0008_resume_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True, verbose_name='Summary'),
        ),
    ]
