# Generated by Django 3.1.3 on 2021-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0010_auto_20210114_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdesc',
            name='jobtext',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='jobtext'),
        ),
    ]
