# Generated by Django 3.1.3 on 2021-01-15 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumeanalyzer', '0013_auto_20210115_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='jobid',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='rate',
        ),
        migrations.AlterField(
            model_name='jobdesc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalyzer.jobdesc')),
                ('resumeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalyzer.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
