# Generated by Django 3.1.3 on 2021-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalyzer', '0014_auto_20210115_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
