# Generated by Django 3.0.7 on 2020-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
