# Generated by Django 3.0.7 on 2020-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_salary',
        ),
        migrations.AddField(
            model_name='service',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='jobs_completed',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='registration_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_offer',
            field=models.TextField(null=True),
        ),
    ]
