# Generated by Django 3.0.7 on 2020-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='jobs_completed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
