# Generated by Django 3.0.7 on 2021-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pcode',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
    ]
