# Generated by Django 3.0.7 on 2021-01-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210107_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
