# Generated by Django 3.0.7 on 2021-01-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210107_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
    ]
