# Generated by Django 3.0.7 on 2020-11-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candedu',
            old_name='cand_id',
            new_name='cand',
        ),
        migrations.RenameField(
            model_name='candexp',
            old_name='cand_id',
            new_name='cand',
        ),
    ]
