# Generated by Django 3.0.7 on 2020-11-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cand', '0002_auto_20201129_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candedu',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='candexp',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='testcand',
            name='timestamp',
        ),
    ]
