# Generated by Django 3.0.7 on 2020-12-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cand', '0003_auto_20201129_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcand',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcand',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
