# Generated by Django 3.0.7 on 2020-12-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201207_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssearch',
            name='total_search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
