# Generated by Django 3.0.7 on 2020-06-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobad',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobad',
            name='employer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
