# Generated by Django 3.0.7 on 2020-06-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20200608_0610'),
        ('jobads', '0002_auto_20200611_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobad',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='jobad',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
        ),
    ]
