# Generated by Django 3.0.7 on 2020-06-11 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20200608_0610'),
        ('jobads', '0003_auto_20200611_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='employer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
        ),
    ]
