# Generated by Django 3.0.7 on 2020-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0005_remove_jobad_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
