# Generated by Django 3.0.7 on 2020-06-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0007_jobad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
