# Generated by Django 3.0.7 on 2020-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0009_auto_20200728_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobad',
            name='area',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='state',
        ),
        migrations.AddField(
            model_name='jobad',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='monthly_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
