# Generated by Django 3.0.7 on 2020-09-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0010_auto_20200728_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobad',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='jobad',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
