# Generated by Django 3.0.7 on 2020-09-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0011_auto_20200911_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='max_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='min_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
