# Generated by Django 3.0.7 on 2020-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0012_auto_20200911_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
