# Generated by Django 3.0.7 on 2020-12-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0014_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview',
            new_name='cand',
        ),
    ]
