# Generated by Django 3.0.7 on 2020-12-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_cand', '0003_auto_20201129_0946'),
        ('jobads', '0015_auto_20201209_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unprocessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_cand.TestCand')),
                ('jobad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.JobAd')),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_cand.TestCand')),
                ('jobad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.JobAd')),
            ],
        ),
        migrations.CreateModel(
            name='NotSuitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_cand.TestCand')),
                ('jobad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.JobAd')),
            ],
        ),
    ]
