# Generated by Django 3.0.7 on 2020-12-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0018_unprocessed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hidden',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notsuitable',
            name='hidden',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='hidden',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
