# Generated by Django 3.0.7 on 2021-01-01 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_cand', '0004_auto_20201218_1644'),
        ('jobads', '0019_auto_20201231_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField(verbose_name='Date')),
                ('booked_time', models.TimeField(verbose_name='Time')),
                ('messages', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_cand.TestCand')),
                ('jobad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.JobAd')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
