# Generated by Django 3.0.7 on 2021-01-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0020_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='closing_date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
