# Generated by Django 3.1.3 on 2021-01-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0022_auto_20210110_0901'),
        ('jobads', '0021_joblist_personality'),
    ]

    operations = [
    ]
