# Generated by Django 3.1.3 on 2021-01-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobads', '0023_merge_20210111_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('openess', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('extraversion', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('chart', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobad',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='max_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='min_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='personality',
        ),
        migrations.AddField(
            model_name='test_employee',
            name='JobAd_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.jobad'),
        ),
        migrations.AddField(
            model_name='test_employee',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobads.joblist'),
        ),
    ]
